export enum ParameterNode {
  CATEGORIES = 'PARAM_CATEGORIES_NODE',
  BRANDS = 'PARAM_BRANDS_NODE',
  COLORS = 'PARAM_COLORS_NODE',
  UNITS = 'PARAM_UNITS_NODE',
  BANKS = 'PARAM_BANKS_NODE',
  DISTRICTS = 'PARAM_DISTRICTS_NODE',
  PROVINCES = 'PARAM_PROVINCES_NODE',
  DEPARTAMENTS = 'PARAM_DEPARTAMENTS_NODE',
}
