import { IMenu } from '@interfaces/index';

export const CONST_MENU: Array<IMenu> = [
  {
    id: 1,
    icon: 'pi pi-chart-line',
    name: 'Menu',
    node: 'MENU_PARAMS',
    typeMenu: 'FATHER',
    code: 'FATHER_MENU',
    route: '',
    children: [
      {
        id: 3,
        icon: 'pi pi-chart-line',
        name: 'Dashboard',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_DASHBOARD',
        typeMenu: 'CHILD',
        route: '/dashboard',
        children: [],
      },
      {
        id: 4,
        icon: 'pi pi-chart-line',
        name: 'Productos',
        node: 'MENU_CHILD_PARAMS',
        typeMenu: 'CHILD',
        code: 'CHILD_DASHBOARD',
        route: '/products',
        children: [
          {
            id: 16,
            icon: 'pi pi-home',
            name: 'Listar Productos',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_LIST_PRODUCTS',
            typeMenu: 'GRAND_CHILD',
            route: '/list-products',
            children: [],
          },
          {
            id: 17,
            name: 'Categorias',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_CATEGORIES',
            typeMenu: 'GRAND_CHILD',
            route: '/categories',
            icon: 'pi pi-chart-line',
            children: [],
          },
          {
            id: 18,
            icon: 'pi pi-chart-line',
            name: 'Marcas',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_BRANDS',
            typeMenu: 'GRAND_CHILD',
            route: '/brands',
            children: [],
          },
        ],
      },
      {
        id: 5,
        icon: 'pi pi-chart-line',
        name: 'Inventario',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_INVENTARY',
        typeMenu: 'CHILD',
        route: '/inventary',
        children: [
          // {
          //   id: 19,
          //   icon: 'pi pi-chart-line',
          //   name: 'Sotck Actual',
          //   node: 'MENU_GRAND_CHILD_PARAMS',
          //   code: 'GRAND_CHILD_CURRENT_STOCK',
          //   typeMenu: 'GRAND_CHILD',
          //   route: '/current-stock',
          //   children: [],
          // },
          // {
          //   id: 20,
          //   icon: 'pi pi-chart-line',
          //   code: 'GRAND_CHILD_INPUT_STOCK',
          //   name: 'Entradas de stock',
          //   node: 'MENU_GRAND_CHILD_PARAMS',
          //   typeMenu: 'GRAND_CHILD',
          //   route: '/input-stock',
          //   children: [],
          // },
          // {
          //   id: 21,
          //   icon: 'pi pi-chart-line',
          //   name: 'Salidas de stock',
          //   node: 'MENU_GRAND_CHILD_PARAMS',
          //   code: 'GRAND_CHILD_OUTPUT_STOCK',
          //   typeMenu: 'GRAND_CHILD',
          //   route: '/output-stock',
          //   children: [],
          // },
          {
            id: 22,
            icon: 'pi pi-chart-line',
            name: 'Ajustes de inventario',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_SETTINGS_INVENTARY',
            typeMenu: 'GRAND_CHILD',
            route: '/settings-inventary',
            children: [],
          },
          {
            id: 23,
            icon: 'pi pi-chart-line',

            name: 'Almacenes',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_WAREHOUSES',
            typeMenu: 'GRAND_CHILD',
            route: '/warehouses',
            children: [],
          },
        ],
      },
      {
        id: 6,
        icon: 'pi pi-chart-line',
        name: 'Ventas',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_PURCHASES',
        typeMenu: 'CHILD',
        route: '/purchases',
        children: [
          {
            id: 24,
            icon: 'pi pi-chart-line',
            name: 'Lista de ventas',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_PURCHASE_LIST',
            typeMenu: 'GRAND_CHILD',
            route: '/purchase-list',
            children: [],
          },
          {
            id: 25,
            icon: 'pi pi-chart-line',
            name: 'Metodos de pago',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_METHODS_PAYMENT',
            typeMenu: 'GRAND_CHILD',
            route: '/methods-payment',
            children: [],
          },
          {
            id: 26,
            icon: 'pi pi-chart-line',
            name: 'Facturas / Boletas',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_COMPROBANTS',
            typeMenu: 'GRAND_CHILD',
            route: '/comprobants',
            children: [],
          },
        ],
      },
      {
        id: 7,
        icon: 'pi pi-chart-line',
        code: 'CHILD_CLIENTS',
        name: 'Clientes',
        node: 'MENU_CHILD_PARAMS',
        typeMenu: 'CHILD',
        route: '/clients',
        children: [
          {
            id: 27,
            icon: 'pi pi-chart-line',
            name: 'Lista de clientes',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_CLIENTS_LIST',
            typeMenu: 'GRAND_CHILD',
            route: '/clients-list',
            children: [],
          },
          {
            id: 28,
            icon: 'pi pi-chart-line',
            name: 'Historial de compras',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_HISTORY_PURCHASE',
            typeMenu: 'GRAND_CHILD',
            route: '/history-purchase',
            children: [],
          },
          {
            id: 29,
            icon: 'pi pi-chart-line',

            name: 'Clientes frecuentes',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_CLIENTS_FRECUENTLY',
            typeMenu: 'GRAND_CHILD',
            route: '/clients-frecuently',
            children: [],
          },
        ],
      },
      {
        id: 8,
        icon: 'pi pi-chart-line',
        name: 'Proveedores',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_SUPPLIERS',
        typeMenu: 'CHILD',
        route: '/suppliers',
        children: [
          {
            id: 30,
            icon: 'pi pi-chart-line',
            name: 'Lista de proveedores',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_SUPPLIERS_LIST',
            typeMenu: 'GRAND_CHILD',
            route: '/suppliers-list',
            children: [],
          },
          {
            id: 31,
            icon: 'pi pi-chart-line',
            name: 'Ordenes de compra',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_ORDERS_PURCHASE',
            typeMenu: 'GRAND_CHILD',
            route: '/orders-purchase',
            children: [],
          },
          {
            id: 32,
            icon: 'pi pi-chart-line',
            name: 'Ingreso de mercaderia',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_INGRESS_MERCANCY',
            typeMenu: 'GRAND_CHILD',
            route: '/ingress-mercancy',
            children: [],
          },
          {
            id: 33,
            icon: 'pi pi-chart-line',
            name: 'Costos',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_COST',
            typeMenu: 'GRAND_CHILD',
            route: '/cost',
            children: [],
          },
        ],
      },
      {
        id: 9,
        icon: 'pi pi-chart-line',
        name: 'Finanzas',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_FINANCE',
        typeMenu: 'CHILD',
        route: '/finance',
        children: [
          {
            id: 34,
            icon: 'pi pi-chart-line',
            name: 'Ingresos / Egresos',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_INPUTS_OUTPUTS',
            typeMenu: 'GRAND_CHILD',
            route: '/inputs-outputs',
            children: [],
          },
          {
            id: 35,
            icon: 'pi pi-chart-line',
            name: 'Ganancias / Perdidas',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_GANANCY',
            typeMenu: 'GRAND_CHILD',
            route: '/ganancy',
            children: [],
          },
          {
            id: 36,
            icon: 'pi pi-chart-line',
            name: 'Gastos fijos',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_GASTOS_FIJOS',
            typeMenu: 'GRAND_CHILD',
            route: '/gastos-fijos',
            children: [],
          },
          {
            id: 37,
            icon: 'pi pi-chart-line',
            name: 'Reportes financieros',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_REPORTS_FINANCIES',
            typeMenu: 'GRAND_CHILD',
            route: '/reports-financies',
            children: [],
          },
        ],
      },
      {
        id: 10,
        icon: 'pi pi-chart-line',
        name: 'Reportes',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_REPORTS',
        typeMenu: 'CHILD',
        route: '/reports',
        children: [],
      },
      {
        id: 11,
        icon: 'pi pi-chart-line',
        name: 'Promociones',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_PROMOTIONS',
        typeMenu: 'CHILD',
        route: '/promotions',
        children: [
          {
            id: 38,
            icon: 'pi pi-chart-line',
            name: 'Cupones',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_CUPONS',
            typeMenu: 'GRAND_CHILD',
            route: '/cupons',
            children: [],
          },
          {
            id: 39,
            icon: 'pi pi-chart-line',
            name: 'Ofertas',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_OFFERS',
            typeMenu: 'GRAND_CHILD',
            route: '/offers',
            children: [],
          },
          {
            id: 40,
            icon: 'pi pi-chart-line',
            name: 'Promociones por producto',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_PROMOTIONS_BY_PRODUCT',
            typeMenu: 'GRAND_CHILD',
            route: '/promotions-by-product',
            children: [],
          },
          {
            id: 41,
            icon: 'pi pi-chart-line',
            name: 'Promociones por tiempo',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_PROMOTIONS_BY_TIME',
            typeMenu: 'GRAND_CHILD',
            route: '/promotions-by-time',
            children: [],
          },
        ],
      },
      {
        id: 12,
        icon: 'pi pi-chart-line',
        name: 'Usuarios y roles',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_USERS_AND_ROLES',
        typeMenu: 'CHILD',
        route: '/users-and-roles',
        children: [
          {
            id: 42,
            icon: 'pi pi-chart-line',
            name: 'Usuarios',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_USERS',
            typeMenu: 'GRAND_CHILD',
            route: '/users',
            children: [],
          },
          {
            id: 43,
            icon: 'pi pi-chart-line',

            name: 'Roles',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_ROLES',
            typeMenu: 'GRAND_CHILD',
            route: '/roles',
            children: [],
          },
          {
            id: 44,
            icon: 'pi pi-chart-line',

            name: 'Permisos',
            node: 'MENU_GRAND_CHILD_PARAMS',
            code: 'GRAND_CHILD_PERMISES',
            typeMenu: 'GRAND_CHILD',
            route: '/permises',
            children: [],
          },
        ],
      },
      {
        id: 13,
        icon: 'pi pi-chart-line',
        name: 'Auditoria',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_AUDIT',
        typeMenu: 'CHILD',
        route: '/audit',
        children: [],
      },
    ],
  },
  {
    id: 2,
    icon: 'pi pi-chart-line',
    name: 'Aplicación',
    node: 'MENU_PARAMS',
    typeMenu: 'FATHER',
    code: 'FATHER_APLICATION',
    route: '',
    children: [
      {
        id: 14,
        icon: 'pi pi-chart-line',
        name: 'Preferecias',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_SETTINGS',
        typeMenu: 'CHILD',
        route: '/settings',
        children: [],
      },
      {
        id: 15,
        icon: 'pi pi-chart-line',
        name: 'Rendimiento',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_PERFORMANCE',
        typeMenu: 'CHILD',
        route: '/performance',
        children: [],
      },
      {
        id: 45,
        icon: 'pi pi-chart-line',
        name: 'Impresion',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_PRINTER',
        typeMenu: 'CHILD',
        route: '/printer',
        children: [],
      },
      {
        id: 46,
        icon: 'pi pi-chart-line',
        name: 'Idioma',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_IDIOMA',
        typeMenu: 'CHILD',
        route: '/idioma',
        children: [],
      },
      {
        id: 47,
        icon: 'pi pi-chart-line',
        name: 'Moneda',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_CURRENCY',
        typeMenu: 'CHILD',
        route: '/currency',
        children: [],
      },
      {
        id: 48,
        icon: 'pi pi-chart-line',
        name: 'Envios',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_SHARED',
        typeMenu: 'CHILD',
        route: '/shared',
        children: [],
      },
      {
        id: 49,
        icon: 'pi pi-chart-line',
        name: 'Impuestos',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_IMPUESTOS',
        typeMenu: 'CHILD',
        route: '/impuestos',
        children: [],
      },
      {
        id: 50,
        icon: 'pi pi-chart-line',
        name: 'Parametros globales',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_PARAMETERS',
        typeMenu: 'CHILD',
        route: '/parameters',
        children: [],
      },
      {
        id: 51,
        icon: 'pi pi-chart-line',
        name: 'Datos del negocio',
        node: 'MENU_CHILD_PARAMS',
        code: 'CHILD_DATA_BUSSINES',
        typeMenu: 'CHILD',
        route: '/data-bussines',
        children: [],
      },
    ],
  },
];
